config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end
    
  def new
    @task = Task.new
  end
  
  def create
    @task = Task.new(params[:tasks])
    @task.save

    redirect_to task_path(@task)
  end


  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(params[:tasks])
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to task_path(@task)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit a task</h1>

<%= form_for(@task) do |item|%>
<p>
  <%= item.label :title %>
    <br />
  <%= item.text_field :title %>
</p>

<p>

  <%= item.label :details%>
    <br />
  <%= item.text_field :details%>

</p>

<p>
  <%= item.submit "Edit a Task" %>
</p>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= task.completed %> <%= link_to "#{task.title}", task_path(task) %>
    </li>
  <% end %>

</ul>

<p>
  <%= link_to "Add Task", tasks_new_path %>
</p>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= form_for(@task) do |item|%>
<p>
  <%= item.label :title %>
    <br />
  <%= item.text_field :title %>
</p>

<p>

  <%= item.label :details%>
    <br />
  <%= item.text_field :details%>

</p>

<p>
  <%= item.submit "Add Task" %>
</p>
<% end %>

app/views/tasks/show.html.erb
<h1>Task info</h1>
    <p><%= @task.title%></p>
    <p><%= @task.completed%></p>
    <p><%= @task.details%></p>

<p>
  <%= link_to 'All Tasks', tasks_path %>
</p>

<p>
  <%= link_to 'Edit a task', edit_task_path(@task) %>
</p>

<p>
  <%= link_to 'Remove a task', task_path(@task), method: :delete, data: { confirm: 'Are you Sure?' } %>
</p>